### ISSUE TITLE
Error using $make after installing 

### ISSUE THREAD

**Issue by woobin3069** [OpenSourceBrain/CelegansNeuromechanicalGaitModulation#1]
Hello, I was following install/usage guide from: https://github.com/openworm/robots/tree/master/WormSim
I successfully installed it,
and no error seem to be appear from make or make install command

But when I go to Model folder and typed "make",
```
g++ -O3 -I ../Sundials/include -Wno-deprecated    -c -o worm.o worm.cc
worm.cc:24:10: fatal error: ida/ida.h: No such file or directory
   24 | #include <ida/ida.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: worm.o] Error 1
woobin@ubuntu:~/CelegansNeuromechanicalGa
```
This error appeared.

I tried to solve this error, but I was unable to solve it.
Is there any way I can solve this?
Thank you.

**Comment by pgleeson** [comment]
Hi @woobin3069. It's quite an old repo, but the code should still run fine. 

I've tested it on both my Mac and an Ubuntu machine and it built/ran fine, and I've added some continuous integration tests [here](https://github.com/OpenSourceBrain/CelegansNeuromechanicalGaitModulation/actions) to try building and executing it, and it seems to all work ok. 

Which version of Ubuntu are you using?

**Comment by woobin3069** [comment]
@pgleeson  It's 20.04! Thank you for response :)

**Comment by woobin3069** [comment]
It was my mistake! Solved!

**Comment by pgleeson** [comment]
Glad you fixed the issue @woobin3069
